export const DOCUMENT_TITLE = '프론트엔드 개발자 김계승 이력서'
export const EMAIL = 'kimkyeseung@gmail.com'
export const PHONE_NUMBER = '010 - 2848 - 9508'
export const GITHUB_URL = 'https://github.com/kimkyeseung'
export const ADDRESS = '서울 영등포구 당산동'
